{application,vmq_k8s,
             [{description,"VMQ Kubernetes Helper Plugin"},
              {vsn,"0.0.0+build.65.ref44adcef"},
              {registered,[]},
              {mod,{vmq_k8s_app,[]}},
              {applications,[kernel,stdlib,yamerl]},
              {env,[]},
              {modules,[vmq_k8s_app,vmq_k8s_reloader,vmq_k8s_sup]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
